interface PlayerData {
  name: string;
  uplay_id: string;
  platform: string;
  specialization: string;
  gearscore: number;
  ecredits: number;
  commendations: number;
  xp_clan: number;
  xp_clan_24h: number | null;
  xp_clan_7d: number | null;
  xp_clan_30d: number | null;
  level_pve: number;
  kills_npc: number;
  timeplayed_pve: number;
  xp_ow: number;
  xp_ow_24h: number | null;
  xp_ow_7d: number | null;
  xp_ow_30d: number | null;
  kills_pve_hyenas: number;
  kills_pve_outcasts: number;
  kills_pve_blacktusk: number;
  kills_pve_truesons: number;
  level_dz: number;
  xp_dz: number;
  xp_dz_24h: number | null;
  xp_dz_7d: number | null;
  xp_dz_30d: number | null;
  timeplayed_dz: number;
  timeplayed_rogue: number;
  maxtime_rogue: number;
  kills_pvp_dz_rogue: number;
  kills_pve_dz_hyenas: number;
  kills_pve_dz_outcasts: number;
  kills_pve_dz_blacktusk: number;
  kills_pve_dz_truesons: number;
  kills_pvp_dz_total: number;
  kills_pvp_elitebosses: number;
  kills_pvp_namedbosses: number;
  xp_pvp: number;
  level_pvp: number;
  kills_pvp: number;
  timeplayed_pvp: number;
  timeplayed_total: number;
  kills_total: number;
  looted: number;
  headshots: number;
  kills_bleeding: number;
  kills_shocked: number;
  kills_burning: number;
  kills_ensnare: number;
  kills_headshot: number;
  kills_skill: number;
  kills_turret: number;
  kills_wp_pistol: number;
  kills_wp_grenade: number;
  kills_wp_smg: number;
  kills_wp_shotgun: number;
  kills_wp_rifles: number;
  kills_specialization: number;
}
